using Monapay.Net.Helpers;
using System;
using System.Collections.Generic;
using System.Text;

namespace Monapay.Net.Models
{
    public class InitializePaymentRequestModel
    {
        /// <summary>
        /// [reference_id] - Max length: 50 This is a unique transaction id generated by the developer for his/her reference purpose
        /// Avoid the use of special character. e.g: kotr20170208125856
        /// </summary>
        public string reference_id { get; set; }= Generator.GenerateReference();
        /// <summary>
        /// [merchant_id] - Developer merchant account id
        /// </summary>
        public string merchant_id { get; set; }
        /// <summary>
        /// [product_key] - Product key, this is NOT the product secret key
        /// </summary>
        public string product_key { get; set; }
        /// <summary>
        /// [uuid] - This is user device id also known as guid, it will be advisable to rip off all special characters, in case of web app, a guid value can be generated and keep in broswer localstorage or cookie for later use, this will help in unique identification of a user or their browser.
        /// </summary>
        public string uuid { get; set; } = Generator.GenerateReference();
        /// <summary>
        /// [amount] - Amount in lowest unit, kobo for Nigerian currency
        /// </summary>
        public int amount { get; set; }
        /// <summary>
        /// [description] - Max length: 100; Short description of the transaction
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// [redirect_url] - OPTIONAL; Redirect url after transaction is complete
        /// </summary>
        public string redirect_url { get; set; } = null;
    }
}
